---
version: "2"
services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM="claim-7say3GUTACDQVRbPn1w8"
    volumes:
      - ~/docker-services/plex/config:/config
      - /mnt/mediastorage/data/media:/data/media
    ports:
      - 32400:32400
    restart: unless-stopped

  # transmission:
  #   image: linuxserver/transmission
  #   container_name: transmission
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Paris
  #     - TRANSMISSION_WEB_HOME=/combustion-release/
  #   volumes:
  #     - ~/docker-services/transmission/config:/config
  #     - /mnt/mediastorage/data/torrents:/downloads:rw
  #     - ~/docker-services/combustion-release:/combustion-release
  #   ports:
  #     - 9091:9091
  #     - 49153:49153
  #     - 49153:49153/udp
  #   restart: unless-stopped

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ~/docker-services/deluge/config:/config
      - /mnt/mediastorage/data/torrents:/downloads
    ports:
      - 8112:8112
      - 52521:52521
      - 52521:52521/udp
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - RUN_OPTS=run options here #optional
    volumes:
      - ~/docker-services/jackett/config:/config
      - /mnt/mediastorage/data/torrents:/downloads:rw
    ports:
      - 9117:9117
    restart: unless-stopped


  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - UMASK_SET=022 #optional
    volumes:
      - ~/docker-services/sonarr/config:/config
      - /mnt/mediastorage/data:/data
      - /mnt/mediastorage/data/torrents:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ~/docker-services/radarr/config:/config
      - /mnt/mediastorage/data:/data
      - /mnt/mediastorage/data/torrents:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - BASE_URL=/ombi #optional
    volumes:
      - ~/docker-services/ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped