---
version: "3"
services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ~/docker-services/plex/config:/config
      - /mnt/media/data/media:/data/media
    ports:
      - 32400:32400
    restart: unless-stopped
    network_mode: "host"

  # deluge:
  #   image: lscr.io/linuxserver/deluge:latest
  #   container_name: deluge
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Paris
  #     - DELUGE_LOGLEVEL=error #optional
  #   volumes:
  #     - ~/docker-services/deluge/config:/config
  #     - /mnt/media/data/torrents:/downloads
  #   ports:
  #     - 8112:8112
  #     - 52522:52522
  #     - 52522:52522/udp
  #   restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:14.3.9
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - WEBUI_PORT=8080
    volumes:
      - ~/docker-services/qbittorrent/config:/config
      - /mnt/media/data/torrents:/data/torrents
    ports:
      - 8080:8080
      - 54855:54855
      - 54855:54855/udp
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - RUN_OPTS=run options here #optional
    volumes:
      - ~/docker-services/jackett/config:/config
      #- /mnt/media/data/torrents:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - UMASK_SET=022 #optional
    volumes:
      - ~/docker-services/sonarr/config:/config
      - /mnt/media/data:/data
      #- /mnt/media/data/torrents:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ~/docker-services/radarr/config:/config
      - /mnt/media/data:/data
      #- /mnt/media/data/torrents:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  speedtest:
    restart: unless-stopped
    container_name: openspeedtest
    ports:
        - '3000:3000'
        - '3001:3001'
    image: openspeedtest/latest

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ~/docker-services/heimdall/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - /mnt/media/data/yt:/downloads
